### PR TITLE
FIX: Sorting to use `Date` by default

### LINKED ISSUE #363: Change default sorting of Notebooks
The "discovery" algorithm continue to give too much weight to popular notebooks and not enough weight to new content. 

In the short term we should enable date ordering as the default view to encourage new contributions.

### PR DESCRIPTION
**Pull request by AakashGfude**
fixes https://github.com/QuantEcon/Bookshelf/issues/363

### CODE REVIEW

**Comment by jstac** [comment]
Many thanks @AakashGfude .  I'll leave it for you and @mmcky to review and merge.

**Comment by mmcky** [comment]
thanks @AakashGfude 

Do we need to figure out credentials or are you able to merge and push this change? 

Does this application need to be built -- It has been in so long I wonder if there will be any compilation issues. Is there a way to test this before deployment?

**Comment by AakashGfude** [comment]
@mmcky yes it will be most recent to least recent. Since this change only targets the front-end API calls, so hopefully should be less prone to compilation issues. I will look for the deployment credentials. I am setting up the system in my present machine as well, for future purposes. Will merge this after testing properly

**Comment by mmcky** [comment]
@AakashGfude looks like I have shared the `certificate` for notes.quantecon.org with you via lastpass

**Pull request merged**
